apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: default
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    app: mysql
  type: NodePort