apiVersion: v1
kind: Service
metadata:
  labels:
    app: msql
  name: msql
  namespace: default
spec:
  ports:
  - port: 90
    protocol: TCP
    targetPort: 80
  selector:
    app: msql
  type: NodePort